### ISSUE TITLE
Potential Spam Bot?

### ISSUE THREAD

**Issue by jayliu50** [werwack/storyliner-support#11]
Also, the same day I filed the issues, I received 2 emails looking like this. Is perhaps a bot listening for new issues on this repo and sending this out to issue submitters?

![image](https://github.com/user-attachments/assets/50d2456f-d9e1-42ec-af92-be51410d6261)

**Comment by werwack** [comment]
Thank you for reporting this. I'll have a close look at that. That's weird.

**Comment by werwack** [comment]
I also received the "bot" mail. I don't know where it comes from. Happened only once so far.
I keep an eye on it.

**Comment by werwack** [comment]
Without further information on this, I close the issue.
