### ISSUE TITLE
The discord link in the project README.md is broken (you need a discord.gg/invite link, you cant just copy the url of a channel from the webbrowsers url field)

### ISSUE THREAD

**Issue by ItsCubeTime** [werwack/storyliner-support#2]

**Comment by werwack** [comment]
Hi @ItsCubeTime ,
I do apologize for the (very) late answer. StoryLiner is on the way but still not completely ready for launch...

Thank you for your feedback about the Discord link. The link has been updated, the Discord is accessible.

Best regards,

Werwack
